"""Public portable authority, execution, acceptance and verification decisions.

All public functions are available here and from their documented submodules.
The core performs no provider side effects and does not authenticate observations.
"""

from .acceptance import (acceptance_contract, refine_acceptance, evaluate_obligations,
                         evidence_status_valid, test_criteria)
from .decisions import (CoreError, completion_transition, goal_projection,
                        merge_authority, path_allowed, require_merge_identity,
                        require_revision_identity, risk_rank, trusted_checks_pass,
                        evaluate_trusted_checks)
from .execution import (context_checkpoint, context_files, context_view, fingerprint, model_call_action,
                        next_attempt, next_phase, recovery_actions, repair_target,
                        retirement, retry_preconditions, upgrade_boundary,
                        verification_transition)
from .verification import (EVIDENCE_CONTRACT, acceptance_evidence,
                           evaluate_goal_conditions, evaluate_predicates, identity,
                           test_failure_kind, validate_bindings,
                           validate_goal_conditions, validate_predicates)

from .schema import SchemaValidationError, SUPPORTED_SCHEMA_KEYWORDS, validate_instance, validate_schema
from .usage import TOKEN_FIELDS, validate_usage
from .prompting import stable_prompt_json, compact_prompt_schema
from .workflow import (WORKFLOW_CONTRACT, graph_level, required_reviews,
                       workflow_transition, require_workflow_evidence)

__version__ = "1.9.2"
# Generated by scripts/generate_contracts.py from config/contract-set.json.
CONTRACT = 'autonomous-control-plane/v1'

__all__ = [
    "stable_prompt_json", "compact_prompt_schema",
    "model_call_action",
    "SchemaValidationError", "SUPPORTED_SCHEMA_KEYWORDS", "validate_instance", "validate_schema",
    "WORKFLOW_CONTRACT", "graph_level", "required_reviews", "workflow_transition",
    "require_workflow_evidence", "CONTRACT", "EVIDENCE_CONTRACT", "CoreError", "__version__",
    "acceptance_contract", "refine_acceptance", "acceptance_evidence", "completion_transition",
    "context_checkpoint", "context_files", "context_view", "evaluate_goal_conditions",
    "evaluate_obligations", "evaluate_predicates", "evidence_status_valid",
    "fingerprint", "goal_projection", "identity", "merge_authority", "next_attempt",
    "next_phase", "path_allowed", "recovery_actions", "repair_target",
    "require_merge_identity", "require_revision_identity", "retirement",
    "retry_preconditions", "risk_rank", "test_criteria", "test_failure_kind",
    "trusted_checks_pass", "evaluate_trusted_checks", "upgrade_boundary", "validate_bindings",
    "validate_goal_conditions", "validate_predicates", "verification_transition",
    "TOKEN_FIELDS", "validate_usage",
]
